### ISSUE TITLE
Option to use the system font

### ISSUE THREAD

**Issue by rharish101** [msfjarvis/compose-lobsters#387]
Currently Claw not only uses it's own font, but also a much larger font size.

For comparison, here's [Glider for Hackernews](https://github.com/Mosc/Glider):
![Screenshot_2023-07-15-09-51-07-078_nl viter glider](https://github.com/msfjarvis/compose-lobsters/assets/25344287/bcbd159d-e805-4b7c-bffe-ca34959c0871)

And here's Claw:
![Screenshot_2023-07-15-09-51-59-383_dev msfjarvis claw android](https://github.com/msfjarvis/compose-lobsters/assets/25344287/3cd690b7-cf03-4d60-bdb1-c742df3cf532)

**Comment by msfjarvis** [comment]
The font size itself isn't actually that big, it's a matter of how scaling is interpreted by the respective UI toolkits used by both apps. Glider is built with Flutter, and Claw uses Jetpack Compose. IMO Compose scaling the text up is correct for the density you're using your device with even if it may feel otherwise. Here's a screenshot of how it looks like on my end with a higher DPI

![Screenshot_20230716-124802.png](https://github.com/msfjarvis/compose-lobsters/assets/13348378/e9e8ffcb-56a0-463e-bcf2-030abcb934a4)

**Comment by rharish101** [comment]
Okay, but what about the font family? Could we at least use the font used by the system?

**Comment by msfjarvis** [comment]
> Okay, but what about the font family? Could we at least use the font used by the system?

I'll see if it's something I can easily provide an option for.

**Comment by msfjarvis** [comment]
Font scaling might be better with the current snapshot build (due to changes in Compose): https://github.com/msfjarvis/compose-lobsters/releases/tag/nightly
